name: (main) Build Dev Container

on:
  push:
    branches:
      - dev-container # TODO replace with main 1

jobs:
  build:
    name: Build Dev Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/dev-container:latest
          cache-from: type=gha,scope=${{ github.repository }}
          cache-to: type=gha,scope=${{ github.repository }},mode=max

